#!/bin/bash
### BEGIN INIT INFO
# Provides:          Ubuntu 16.04 LTS
# Required-Start:    $all
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
. /lib/lsb/init-functions
VM_USER="root" # Your username
SU="sudo -H -u $VM_USER "
VM="f64b7808-4f3f-430d-9679-ca9db52bd943" # VMachine ID
#----------------------
VMSTATUS=`$SU VBoxManage showvminfo $VM |grep "State:"|awk 'NR<2{print $2}'`
# Output info ---------------------
VMRUNS2=`$SU VBoxManage list -l runningvms|grep "Name:"`
VMRUNS=`$SU VBoxManage list vms | awk '{print $1}' | tr -d \"`
echo
echo -e "\e[0;36m===============================\e[00m"
echo -e "\e[01;33m Virtual Machines List:\e[00m"
echo
for line in $VMRUNS
do
  se_wd=`echo $VMRUNS2 | grep $line`
  if [ -z "$se_wd" ]
  then
    echo -e "\e[01;31m OFF $line\e[00m"
  else
    echo -e "\e[01;32m ON  $line\e[00m"
  fi
done
echo -e "\e[0;36m===============================\e[00m"
echo
#---------------------------------------


case "$1" in
  start)
  if [ $VMSTATUS != "running" ]
  then
    log_daemon_msg "Starting VirtualBox $VM machine"
    $SU VBoxManage startvm $VM --type headless
    log_end_msg 0
  fi
  ;;
  restart)
  log_daemon_msg "Reseting VirtualBox $VM machine"
  $SU VBoxManage controlvm $VM reset
  log_end_msg 0
  ;;
  stop)
  if [ $VMSTATUS != "saved" ]
  then
    log_daemon_msg "Saving state of VirtualBox $VM machine"
    $SU VBoxManage controlvm $VM savestate
    log_end_msg 0
  fi
  ;;
  *)
  echo "Usage: $0 {start|restart|stop}"
  exit 1
  ;;
esac
:
